import axios from 'axios'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import useSWR from 'swr'

const inter = Inter({ subsets: ['latin'] })
const fetcher = (url: string) => axios.get(url).then(res => res.data)

export default function Home() {
  const { data, error, isLoading } = useSWR('api/users', fetcher)
  console.log(data)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      </main>
    </>
  )
}
